---
- name: "Flask APP"
  become: true
  hosts: all
  tasks:
    - name: "Set Fact Values"
      set_fact:
        docker_user: DOCKER_USER
        docker_pass: DOCKER_PASSWORD
        repo: REPO_URL
        image_name: IMAGE_NAME
        ct_name: CONTAINER_NAME
        ct_publish_port: PUBLISH_PORT
        ct_port: CONTAINER_PORT

    - include_tasks: build.yml
      when: inventory_hostname in groups ['Build']  
     

    - include_tasks: test.yml
      when: inventory_hostname in groups ['Test']  
        
              
