---
- name: "Flask APP"
  become: true
  hosts: all
  tasks:
    - name: "Set Fact Values"
      set_fact:
        docker_user: mdockanu
        docker_pass: Manu@DOCKER1996
        repo: https://github.com/ManuGeorge96/simple_flask_app.git
        image_name: fresh_flask
        ct_name: fresh_flask
        ct_publish_port: 80
        ct_port: 5000

    - include_tasks: build.yml
      when: inventory_hostname in groups ['Build']  
     

    - include_tasks: test.yml
      when: inventory_hostname in groups ['Test']  
        
              
